services:
  stardew:
    restart: unless-stopped
    container_name: stardew-server-localmods
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        METHOD: "LOCAL"
    environment:
      - TZ=America/New_York
      - CUSTOM_USER=stardew
      - PASSWORD=stardew
      - TITLE=Stardew Valley Game Server (Local Mods)
    ports:
      - 3100:3000/tcp
      - 3101:3001/tcp
      - 24643:24642/udp
    volumes:
      - ./config:/config/modconfs
      - ./saved_games:/config/.config/StardewValley/Saves
      - type: bind
        source: ./mods
        target: /external-mods
        read_only: true
